export const START_FETCHING_DATA = 'START_FETCHING_DATA';
export const START_FETCHING_INITIAL_DATA = 'START_FETCHING_INITIAL_DATA';
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_INITIAL_DATA = 'FETCH_INITIAL_DATA';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const MINUS_ITEM = 'MINUS_ITEM';
